import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { getCorsHeaders } from "../_shared/cors.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface DocumentAnalysisRequest {
  documentContent: string;
  documentType: 'business_plan' | 'business_model_canvas' | 'market_study';
  title: string;
}

interface AnalysisIssue {
  category: 'business_logic' | 'analytics' | 'financial' | 'decisional' | 'incoherence';
  severity: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  location: string;
  recommendation: string;
}

interface AnalysisResult {
  summary: string;
  overallScore: number;
  strengths: string[];
  issues: AnalysisIssue[];
  recommendations: string[];
}

serve(async (req: Request) => {
  console.log("Function 'analyze-business-document' invoked.");

  const requestOrigin = req.headers.get('Origin');
  const corsHeaders = getCorsHeaders(requestOrigin);

  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { documentContent, documentType, title }: DocumentAnalysisRequest = await req.json();
    
    const geminiApiKey = Deno.env.get("GEMINI_API_KEY");
    if (!geminiApiKey) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    console.log(`Analyzing ${documentType} document: ${title}`);

    const systemPrompt = `You are an expert business analyst specializing in ${documentType.replace(/_/g, ' ')}. 
Analyze the provided document for:
1. Business Logic Issues: Flawed assumptions, unrealistic projections, market misunderstandings
2. Analytics Issues: Missing data, incorrect metrics, poor analysis methodology
3. Financial Issues: Budget errors, revenue model problems, cost structure issues
4. Decisional Issues: Poor strategic choices, conflicting priorities, unclear objectives
5. Incoherence: Contradictions, inconsistencies, misaligned sections

Provide a comprehensive analysis in French.`;

    const analysisPrompt = `
Document Type: ${documentType}
Document Title: ${title}

Content:
${documentContent}

Please analyze this document thoroughly and return your analysis in the following JSON format:
{
  "summary": "A comprehensive summary of the document quality and main findings (2-3 paragraphs in French)",
  "overallScore": 75,
  "strengths": [
    "Strength 1 in French",
    "Strength 2 in French",
    "Strength 3 in French"
  ],
  "issues": [
    {
      "category": "business_logic|analytics|financial|decisional|incoherence",
      "severity": "critical|high|medium|low",
      "title": "Issue title in French",
      "description": "Detailed description of the issue in French",
      "location": "Section or page reference",
      "recommendation": "Specific actionable recommendation in French"
    }
  ],
  "recommendations": [
    "Priority recommendation 1 in French",
    "Priority recommendation 2 in French",
    "Priority recommendation 3 in French"
  ]
}

Focus on:
- Identifying all logical inconsistencies and contradictions
- Validating financial calculations and projections
- Assessing market analysis quality and realism
- Evaluating strategic coherence
- Checking data accuracy and analytical rigor
`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${geminiApiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: `${systemPrompt}\n\n${analysisPrompt}`
            }]
          }],
          generationConfig: {
            temperature: 0.4,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 4096,
          },
          safetySettings: [
            {
              "category": "HARM_CATEGORY_HARASSMENT",
              "threshold": "BLOCK_MEDIUM_AND_ABOVE"
            },
            {
              "category": "HARM_CATEGORY_HATE_SPEECH",
              "threshold": "BLOCK_MEDIUM_AND_ABOVE"
            }
          ]
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error:', errorText);
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const geminiData = await response.json();
    console.log("Gemini response received");

    if (!geminiData.candidates || !geminiData.candidates[0]) {
      throw new Error('No content generated by Gemini');
    }

    const generatedText = geminiData.candidates[0].content.parts[0].text;
    
    let analysisResult: AnalysisResult;
    try {
      const jsonMatch = generatedText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        analysisResult = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('No JSON found in response');
      }
    } catch (parseError) {
      console.warn("Failed to parse JSON, creating fallback analysis");
      
      analysisResult = {
        summary: generatedText.substring(0, 500),
        overallScore: 70,
        strengths: ["Analyse en cours..."],
        issues: [{
          category: 'business_logic',
          severity: 'medium',
          title: 'Analyse détaillée requise',
          description: generatedText,
          location: 'Document complet',
          recommendation: 'Réviser manuellement le document'
        }],
        recommendations: ["Vérifier l'analyse complète ci-dessus"]
      };
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        analysis: analysisResult,
        timestamp: new Date().toISOString()
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );

  } catch (error) {
    console.error("Error in analyze-business-document:", error);
    return new Response(
      JSON.stringify({ 
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
